-- ── orders.status → compact surrogate FK ──────────────────────────────────────
-- Run AFTER order_statuses.sql, in the Supabase SQL editor. Idempotent (safe to
-- re-run; handles a fresh DB, the legacy text-status DB, and an already-migrated DB).
--
-- WHY: orders is a high-volume table. Storing the status as text ('in_production',
-- ~13 bytes) carries that on every row AND inflates every status index (status is a
-- hot filter: "this baker's open orders"). order_statuses is a bounded lookup, so we
-- give it a smallint surrogate `id` and store THAT on orders (2 bytes), keeping the
-- readable `key` UNIQUE on the lookup for humans + the API to join on. This is the
-- scale-correct shape; do NOT reason from today's row count. See INVARIANTS.

-- 1. Surrogate id on the lookup (fills existing rows from the identity sequence).
ALTER TABLE order_statuses ADD COLUMN IF NOT EXISTS id smallint GENERATED BY DEFAULT AS IDENTITY;

-- 2. Keep `key` unique once it is no longer the primary key.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'order_statuses_key_unique') THEN
    ALTER TABLE order_statuses ADD CONSTRAINT order_statuses_key_unique UNIQUE (key);
  END IF;
END $$;

-- 3. Drop the legacy text FK (orders.status → order_statuses.key) so we can re-key.
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_fkey;

-- 4. Move the primary key from `key` to `id` (only if it isn't already on id).
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
    WHERE c.conrelid = 'order_statuses'::regclass AND c.contype = 'p' AND a.attname = 'id'
  ) THEN
    ALTER TABLE order_statuses DROP CONSTRAINT IF EXISTS order_statuses_pkey;
    ALTER TABLE order_statuses ADD PRIMARY KEY (id);
  END IF;
END $$;

-- 5. orders.status_id (the compact FK value).
ALTER TABLE orders ADD COLUMN IF NOT EXISTS status_id smallint;

-- 6. Backfill from the legacy text column while it still exists (maps legacy values
--    too), and refuse to lose any value we don't recognise.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_name = 'orders' AND column_name = 'status') THEN
    UPDATE orders SET status = 'requested'     WHERE status = 'pending';
    UPDATE orders SET status = 'confirmed'     WHERE status = 'approved';
    UPDATE orders SET status = 'in_production'  WHERE status = 'in_progress';
    UPDATE orders SET status = 'completed'      WHERE status = 'delivered';

    UPDATE orders o SET status_id = s.id
      FROM order_statuses s WHERE s.key = o.status AND o.status_id IS NULL;

    IF EXISTS (SELECT 1 FROM orders WHERE status IS NOT NULL AND status_id IS NULL) THEN
      RAISE EXCEPTION 'orders.status has unmapped values: %',
        (SELECT string_agg(DISTINCT status, ', ') FROM orders WHERE status IS NOT NULL AND status_id IS NULL);
    END IF;
  END IF;
END $$;

-- Any remaining NULL (orders created mid-transition) → 'requested'.
UPDATE orders o SET status_id = s.id
  FROM order_statuses s WHERE s.key = 'requested' AND o.status_id IS NULL;

-- 7. FK + the index for the hot access pattern (a baker's orders by status).
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_status_id_fkey') THEN
    ALTER TABLE orders ADD CONSTRAINT orders_status_id_fkey
      FOREIGN KEY (status_id) REFERENCES order_statuses(id);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS orders_baker_status_idx ON orders (baker_id, status_id);

-- 8. Lock status_id in. (The API sets it explicitly on insert — a surrogate id can't
--    be a literal column default.)
ALTER TABLE orders ALTER COLUMN status_id SET NOT NULL;

-- 9. EXPAND/CONTRACT: keep the legacy text `status` column for now, but make it
--    nullable + defaultless so the new code (which writes only status_id) can insert
--    without tripping it. This lets the OLD code keep running until the new code is
--    deployed — zero downtime. Drop it afterwards with order_status_drop_text.sql.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_name = 'orders' AND column_name = 'status') THEN
    ALTER TABLE orders ALTER COLUMN status DROP NOT NULL;
    ALTER TABLE orders ALTER COLUMN status DROP DEFAULT;
  END IF;
END $$;
